import time
import os
import sys
import random

'''Variáveis'''
chave_primeira_sala = False
chave_helicoptero = False
cont_fuzivel = 0
escolha1 = 4
atalho = False
cont_escolha2 = 0
cont1_escolha4 = 0
cont_escolha3 = 0
cont1_escolha4 = 0
cont2_escolha4 = 0
cont3_escolha4 = 0
fuzivel_1 = False
fuzivel_2 = False
lanterna = False
a = 2.5
senha1 = False
senha2 = False

''' Funções'''
def efeitoFala(string):
    for i in string:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(0.05)
def restart():
    python = sys.executable
    os.execl(python, python, * sys.argv)

'''Introdução'''
print("############################")
time.sleep(a)
print("## E S C A P E  D E L E S ##")
time.sleep(a)
print("############################")
time.sleep(a)
print('')
time.sleep(a)
print('')
time.sleep(a)
print("Você acorda em uma sala apertada sentado em uma cadeira com as mãos amarradas pelas costas.")
time.sleep(a)
print("Com um pouco de esforço você consegue soltar as cordas e se desamarrar.")
time.sleep(a)
print("Ao levantar-se da cadeira voce avista uma janela dentro da mesma sala, porem grades impedem que voce escape por ela.")
time.sleep(a)
print("Atravez dela voce observa que se encontra em um edificio abandonado e isolado.")
time.sleep(a)
print("Encostado no pé da cadeira, encontra-se uma mochila.")
time.sleep(a)
print("Você a pega.")
time.sleep(a)
print("Sua memória foi afetada, você nem mesmo se lembra de como chegou nesse local.")
time.sleep(a)
efeitoFala('"Qual era o meu nome mesmo?"')
print('')
time.sleep(a)
print("Digite o nome do personagem:")
nome_jogador = input()
efeitoFala('"Ah, certo, o meu nome é {}."'. format(nome_jogador))
print('')
time.sleep(a)
print("Após lembrar de seu nome, você começa a pensar em métodos para fugir desse estranho local.")
time.sleep(a)
print("Vasculhando a sala, nota-se a existencia de 3 caminhos distintos:")
time.sleep(a)
print("Em sua direita, uma sala escura, é dificil identificar o que há lá dentro.")
time.sleep(a)
print('Na esquerda, uma sala iluminada que aparenta ser acessível.')
time.sleep(a)
print('E à sua frente, uma porta.')
time.sleep(a)
efeitoFala('"Para onde devo ir?"')
print('')
time.sleep(a)

'''Andar 1'''
while lanterna == False:
    print('Digite "D" para seguir pela direita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
    direction = input("")
    time.sleep(a)
    if direction in 'D' 'd':
        print("Você entra na sala, porém não é possivel avistar nada, pois está escuro demais.")
        time.sleep(a)
        print("Você retorna para a sala anterior. Para onde ir agora?")
        time.sleep(a)
    elif direction in 'E' 'e':
         print("Ao adentrar na sala da esquerda, você começa a vasculhar o ambiente.")
         time.sleep(a)
         print("Depois de um tempo procurando, você se depara com uma escrivaninha abandonada, cuja gaveta encontra-se aberta.")
         time.sleep(a)
         print("Na gaveta, você encontrou uma lanterna funcional.")
         time.sleep(a)
         print("Você retorna para a sala onde estava inicialmente amarrado. Para onde ir agora?")
         time.sleep(a)
         print('Digite "D" para seguir pela direita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
         time.sleep(a)
         lanterna = True
    elif direction in 'F' 'f':
        print("Você gira a maçaneta, mas a porta está trancada. Para onde ir agora?")
        time.sleep(a)
    else:
        time.sleep(a)
while lanterna == True:
    direction = input("")
    time.sleep(a)
    if direction in 'D' 'd':
        if chave_primeira_sala == False:
            print("A sala anteriormente escura agora é visível por causa da lanterna pega na gaveta da escrivaninha abandonada.") 
            time.sleep(a)
            print("Por mais que ela esteja funcional, é perceptível que a bateria dessa lanterna não está muito alta.") 
            time.sleep(a)
            print("Chegando no fim da sala você ouve um barulho diferente ao andar.") 
            time.sleep(a)
            print("Ao olhar pra baixo, você percebe que pisou em uma chave.") 
            time.sleep(a)
            print("Você pega a chave e retorna para a sala inicial. Onde ir agora?") 
            time.sleep(a)
            print('Digite "D" para seguir pela dirita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
            time.sleep(a)
            chave_primeira_sala = True
        else:
            print("Não é possível encontrar mais nada nessa sala.")
            time.sleep(a)
            print('Digite "D" para seguir pela dirita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
            time.sleep(a)
    elif direction in 'E' 'e':
        print("Não é possível encontrar mais nada nessa sala.")
        time.sleep(a)
        print('Digite "D" para seguir pela dirita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
        time.sleep(a)
    elif direction in 'F' 'f':
        if chave_primeira_sala == True:
            efeitoFala('"A chave encontrada na sala escura serve perfeitamente nessa fechadura."')
            print('')
            time.sleep(a)
            print("A porta é aberta, revelando uma escada tão longa que o final não é visível.")
            time.sleep(a)
            break
        else:
            print("Você gira a maçaneta, mas a porta está trancada. Onde ir agora?")
            print('Digite "D" para seguir pela direita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
            time.sleep(a)
    else:
        print('Digite "D" para seguir pela dirita // Digite "E" para seguir pela esquerda // Digite "F" para seguir para frente')
        time.sleep(a)

'''Andar 2'''
print("Diante da escada, e com o conhecimento de que não há mais nada para ser feito no último andar, você sobe a escada.")
time.sleep(a)
print("No final da escada, você encontra uma sala pequena.")
time.sleep(a)
print("Nessa sala, são notáveis uma porta aberta e um elevador.")
time.sleep(a)
efeitoFala('"Ok, {}, pense. O que devo fazer agora?"'. format(nome_jogador))
print('')
time.sleep(a)
print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
time.sleep(a)
escolha = int(input())
time.sleep(a)
while fuzivel_1 == False or fuzivel_2 == False:
    if escolha == 1:
        if cont_fuzivel == 0:
            print("Tentar usar o elevador?")
            time.sleep(a)
            print("S - Sim // N-Não")
            time.sleep(a)
            escolha_elevador = input()
            time.sleep(a)
            if escolha_elevador in 'S''s':
                print("Cego pela vontade de sair daquele prédio, você entra no elevador, e precipitadamente, aperta um botão.")
                time.sleep(a)
                print("Inicialmente, nada acontece, porém, após alguns segundos, você ouve um estrondo e sente um leve tranco nos pés.")
                time.sleep(a)
                print("O Elevador despenca.")
                time.sleep(a)
                print("Você morreu.")
                time.sleep(a)
                print("Reiniciar o jogo?")
                time.sleep(a)
                print("1 - Sim // 2 - Não")
                time.sleep(a)
                reiniciar = int(input(""))
                time.sleep(a)
                if reiniciar == 1:
                    restart()
                elif reiniciar == 2:
                    sys.exit()
            else:
                efeitoFala('"Talvez agora não seja a hora"')
                print('')
                time.sleep(a)
                print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
                time.sleep(a)
                escolha = int(input())
                time.sleep(a)
        if cont_fuzivel == 1:
            print("Tentar usar o elevador?")
            time.sleep(a)
            print("S - Sim // N-Não")
            time.sleep(a)
            escolha_elevador = input()
            time.sleep(a)
            if escolha_elevador in 'S''s':
                print("Você encaixa o fusível no circuito do elevador e aperta um botão.")
                time.sleep(a)
                print("Porém, sem sucesso.")
                time.sleep(a)
                print("o elevador não funciona.")
                time.sleep(a)
                print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
                time.sleep(a)
                escolha = int(input())
                time.sleep(a)
            else:
                efeitoFala('"Talvez agora não seja a hora"')
                print('')
                time.sleep(a)
                print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
                time.sleep(a)
                escolha = int(input())
                time.sleep(a)
    elif escolha == 2:
        if cont_escolha2 == 0:
            cont_fuzivel += 1
            fuzivel_1 = True
            cont_escolha2 += 1
            print('Você decide tentar encontrar alguma coisa que possa te ajudar nessa sala.')
            time.sleep(a)
            print('Ao olhar cautelosamente, você percebe uma rachadura na parede do lado do elevador')
            time.sleep(a)
            print('Colocando a mão la dentro, além de muita poeira e teias de aranha, você sente um objeto.')
            time.sleep(a)
            print('Retirando o objeto da rachadura, você o identifica como sendo um fusível.')
            time.sleep(a)
            if cont_fuzivel == 2:
                break
            print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
            time.sleep(a)
            escolha = int(input())
            time.sleep(a) 
        else:
            print("Não há mais nada para ser encontrado aqui.")
            time.sleep(a)
            print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
            time.sleep(a)
            escolha = int(input())
            time.sleep(a) 
    elif escolha == 3:
        if cont_escolha3 == 0:
            cont_escolha3 += 1
            fuzivel_2 = True
            cont_fuzivel += 1
            print('Você decide entrar na sala com a porta aberta')
            time.sleep(a)
            print('Lá dentro, encontra-se uma estante completamente abandonada e coberta por uma espessa camada de poeira.')
            time.sleep(a)
            print('Após vasculhar a estante, você sente um objeto em meio a tanta poeira.')
            time.sleep(a)
            print('Você encontrou um fusivel')
            time.sleep(a)
            if cont_fuzivel == 2:
                break
            print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
            time.sleep(a)
            escolha = int(input())
            time.sleep(a) 
        else:
            print('Não há mais nada aqui.')
            time.sleep(a)
            print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
            time.sleep(a)
            escolha = int(input())
            time.sleep(a)
    else:
        time.sleep(a)
while escolha1 != 1:
    print("1 - Usar o elevador // 2 - Vasculhar a sala // 3 - Ir para a sala ao lado")
    time.sleep(a)
    escolha1 = int(input())
    time.sleep(a) 
    if escolha1 == 2:
        print('Não há mais nada aqui.')
        time.sleep(a) 
    elif escolha1 == 3:
        print('Não há mais nada aqui.')
        time.sleep(a) 
    elif escolha1 == 1:
        print("Após encontrar os dois fusíveis, você decide dar uma chance para o elevador.")
        time.sleep(a) 
        print("Os fusíveis são encaixados no circuito.")
        time.sleep(a) 
        print("No mesmo segundo que o segundo fusível é encaixado, uma luz é acesa, e você ouve uma tradicional musica de elevador.")
        time.sleep(a) 
        print("Você entra e aperta o botão para dirigir-se ao próximo andar.")
        time.sleep(a) 
        print("As portas se fecham, e após alguns segundos, você se encontra no terceiro andar.")
        time.sleep(a) 

'''Andar 3'''
print("Ao sair do elevador você imediatamente nota uma diferença nesse andar.")
time.sleep(a)
print("Ele é um longo corredor com dezendas de celas.")
time.sleep(a)
print("Você tenta abrir uma para ver se encontra algo util, mas sem sucesso.")
time.sleep(a)
print("Então, você resolve seguir em frente.")
time.sleep(a)
print("Chegando na metade do corredor você ouve um som.")
time.sleep(a)
efeitoFala('"Psiu..."')
print('')
time.sleep(a) 
print("Você olha para os lados, porém não vê nada.")
time.sleep(a)
efeitoFala('"Ei, você..."')
print('')
time.sleep(a) 
print("Nervoso, você liga a lanterna para observar seus arredores.")
time.sleep(a) 
print("Apontando a lanterna para uma das celas, você encontra a fonte dos sons.")
time.sleep(a) 
efeitoFala('"Você mesmo, venha cá..."')
print('')
time.sleep(a) 
print("Você se aproxima da cela onde encontra-se um senhor barbado, aparentemente de idade.")
time.sleep(a) 
efeitoFala('"Você é {}, não é?"'.format(nome_jogador))
print('')
time.sleep(a) 
print("Escolha a sua resposta:")
time.sleep(a)
print("1 - Sim. // 2 - Quem é você? // 3 - Ignorar")
time.sleep(a)
escolhaFala = int(input(""))
time.sleep(a)
if escolhaFala == 1:
    efeitoFala('"Sim, sou eu."')
    print('')
    time.sleep(a) 
    efeitoFala('"Fiquei observando sua chegada da minha janela."')
    print('')
    time.sleep(a) 
    efeitoFala('"Você está tentando sair daqui, não está?"')
    print('')
    time.sleep(a) 
    print("Você responde que sim.")
    time.sleep(a) 
    efeitoFala('"Então pegue isso, pode ser mais útil para você do que foi para mim."')
    print('')
    time.sleep(a) 
    print("Você recebe um pedaço de papel sujo, e amarelado.")
    time.sleep(a) 
    print("Nele estão escritos os dígitos 5 2 0 7.")
    time.sleep(a) 
    print("Quando você vai se virar para agradece-lo, você vê os olhos do senhor apagando, enquanto ele lentamente se deita no chão.")
    time.sleep(a) 
    print("Você agradece, porém não recebe uma resposta.")
    time.sleep(a) 
    senha = True
if escolhaFala == 2:
    efeitoFala('"Quem é você?"')
    print('')
    time.sleep(a) 
    efeitoFala('"Ah, meu nome não importa."')
    print('')
    time.sleep(a) 
    efeitoFala('"Fiquei observando sua chegada da minha janela."')
    print('')
    time.sleep(a) 
    efeitoFala('"Parece que você realmente conseguiu escapar deles."')
    print('')
    time.sleep(a) 
    efeitoFala('"Você está tentando sair daqui, não está?"')
    print('')
    time.sleep(a) 
    print('1 - Sim. // 2 - Quem são "eles"?')
    time.sleep(a) 
    resposta = int(input(""))
    time.sleep(a) 
    if resposta == 1:
        efeitoFala('"Então pegue isso, pode ser mais útil para você do que foi para mim."')
        print('')
        time.sleep(a)
        print("Você recebe um pedaço de papel sujo, e amarelado.")
        time.sleep(a)
        print("Nele estão escritos os dígitos 5 2 0 7.")
        time.sleep(a)
        print("Quando você vai se virar para agradece-lo, você vê os olhos do senhor apagando, enquanto ele lentamente se deita no chão.")
        time.sleep(a)
        print("Você agradece, porém não recebe uma resposta.")
        time.sleep(a)
        senha1 = True
    elif resposta == 2:
        efeitoFala('"Mas quem são... eles?"')
        print('')
        time.sleep(a) 
        print("Diante de sua pergunta, o senhor da uma seca risada, e diz:")
        time.sleep(a)
        efeitoFala('"Eu não sei. Eles apagam a memória de todos que são trazidos para cá."')
        print('')
        time.sleep(a) 
        efeitoFala('"A maior parte de nós nunca os viu, e aqueles que os viram, não estão mais conosco."')
        print('')
        time.sleep(a) 
        print("Você olha para os lados, e repara que a maior parte das celas estão vazias, ou com amontuados de objetos não identificáveis.")
        time.sleep(a)
        efeitoFala('"Normalmente não temos o privilégio de andar livremente por aqui..."')
        print('')
        time.sleep(a) 
        efeitoFala('"Então eu imagino que você queira escapar."')
        print('')
        time.sleep(a) 
        efeitoFala('"Mas antes de continuar, pegue isso:"')
        print('')
        time.sleep(a) 
        print("Você recebe um pedaço de papel sujo, e amarelado.")
        time.sleep(a)
        print("Nele estão escritos os dígitos 5 2 0 7.")
        time.sleep(a)
        print("Você agradece o senhor, que lhe deseja boa sorte.")
        time.sleep(a)
        senha1 = True
if escolhaFala == 3:
    print("Você ignora o senhor e dirige-se para o fim do corredor.")
    time.sleep(a)
    efeitoFala('"Não, não vá. Eu posso te ajudar, você está tentando sair daqui. não está?"')
    print('')
    time.sleep(a) 
    print("Você concorda.")
    efeitoFala('"Então pegue isso, pode ser mais útil para você do que foi para mim."')
    print('')
    time.sleep(a) 
    print("Você recebe um pedaço de papel sujo, e amarelado.")
    time.sleep(a)
    print("Nele estão escritos os dígitos 2 4 4 6.")
    time.sleep(a)
    print("Você agradece o senhor, que o responde com um leve sorriso.")
    time.sleep(a)
    senha2 = True
print("Após falar com o senhor que estava preso, você se dirige ao final do corredor.")
time.sleep(a)
print("Na sua frente, uma escada que aparenta levar ao próximo andar, e na sua direita, um elevador que parece estar funcional.")
time.sleep(a)
print("Ambos os caminhos estão livres de obstáculos.")
time.sleep(a)
print("Para onde ir?")
time.sleep(a)
print("1 - Escada // 2 - Elevador")
time.sleep(a)
escolhaFinal = int(input(""))

'''Finais do Jogo'''
if escolhaFinal == 2:
    atalho = True
    print("Você decide ir pelo elevador.")
    time.sleep(a)
    print("O sentimento é que ele está demorando mais que o normal para parar.")
    time.sleep(a)
    print("Quando ele finalmente para, as portas se abrem, e você sente uma forte ventania no rosto.")
    time.sleep(a)
    print("Você agora se encontra na cobertura do prédio.")
    time.sleep(a)
    print("Ao pisar pra fora do elevador você ouve um grande estrondo, e o elevador despenca da cobertura.")
    time.sleep(a)
    print("Agora você se encontra na cobertura do prédio, e não tem como voltar.")
    time.sleep(a)
    print("Ali, você encontra um helicóptero, uma porta, que aparentemente te leva pra dentro do prédio novamente e uma sequência de andaimes, que termina fora do prédio.")
    time.sleep(a)
    print("Qual é a sua decisão?")
    time.sleep(a)
    while atalho == True:
        print("1 - Helicóptero // 2 - Porta // 3 - Andaimes.")
        time.sleep(a)
        escolhaCobertura = int(input(""))
        time.sleep(a)
        if escolhaCobertura == 1:
            print("Você se aproxima do helicóptero.")
            time.sleep(a)
            print("Pensando em usa-lo para escapar, você decide subir.")
            time.sleep(a)
            print("Ao sentar no banco do motorista, percebe-se a ausência de uma chave, ou um mecanismo para ligar o helicóptero")
            time.sleep(a)
            print("Decepcionado, você desce.")
            time.sleep(a)
            print("Para onde ir agora?")
            time.sleep(a)
        elif escolhaCobertura == 2:
            print("A porta não abre por esse lado.")
            time.sleep(a)
        elif escolhaCobertura == 3:
            print("Você decide ir pelos andaimes.")
            time.sleep(a)
            print("Após pisar no primeiro, você sente toda a estrutura balançar, e o medo te consome.")
            time.sleep(a)
            print("Cautelosamente, você desce um por um...")
            time.sleep(a)
            x = random.randrange(1,4)
            if x == 1:
                print("Por mais que toda a estrutura esteja balançando violentamente, você consegue chegar ao chão com segurança.")
                time.sleep(a)
                print("Após chegar no chão, você tira um minuto do seu tempo para contemplar seus arredores,")
                time.sleep(a)
                print("e percebe que não tem nada.")
                time.sleep(a)
                print("Você senta no chão, e vagarosamente fecha os olhos.")
                time.sleep(a)
                efeitoFala(". . .")
                print('')
                time.sleep(a)
                print("Você venceu!")
                time.sleep(a)
                print("Reiniciar o jogo?")
                time.sleep(a)
                print("1 - Sim // 2 - Não")
                time.sleep(a)
                reiniciar = int(input(""))
                time.sleep(a)
                if reiniciar == 1:
                    restart()
                elif reiniciar == 2:
                    sys.exit()
            else:
                print("Chegando na metade da descida, você ouve um forte estralo.")
                time.sleep(a)
                print("Desesperado, você começa a olhar para os lados.")
                time.sleep(a)
                print("Olhando para a sua direita, você percebe que está na frente da cela do senhor que havia te dado a senha.")
                time.sleep(a)
                print("O senhor olha pela janela, olha fixamente para os seus olhos, e solta uma risada.")
                time.sleep(a)
                print("Os andaimes despencam.")
                time.sleep(a)
                print("Você morreu.")
                time.sleep(a)
                print("Reiniciar o jogo?")
                time.sleep(a)
                print("1 - Sim // 2 - Não")
                time.sleep(a)
                reiniciar = int(input(""))
                time.sleep(a)
                if reiniciar == 1:
                    restart()
                elif reiniciar == 2:
                    sys.exit()   

elif escolhaFinal == 1:
    print("Você sobe as escadas, sem muitos obstáculos para te impedir.")
    time.sleep(a)
    print("Chegando lá, você encontra duas portas e um cofre de metal.")
    time.sleep(a)
    print("O Que fazer?")
    time.sleep(a)
    print("1 - Ir para a porta da direita // 2 - Ir para a porta da esquerda // 3 - Tentar abrir o cofre")
    time.sleep(a)
    escolha4 = int(input(""))
    time.sleep(a)
    while True:
        if escolha4 == 1:
            if cont1_escolha4 == 0:
                cont1_escolha4 +=1
                print("Você a abre a porta da direita vagarosamente...")
                time.sleep(a)
                print("Ela está escura. Você liga a sua lanterna para tentar enxergar algo.")
                time.sleep(a)
                print("Lá dentro você encontra o mesmo prisioneiro que te deu a senha. Porém, ele se encontra estático, parado, olhando nos seus olhos.")
                time.sleep(a)
                print("Assustado, você fecha a porta, enquanto ouve uma risada vindo de dentro da sala.")
                time.sleep(a)
                print("O Que fazer?")
                time.sleep(a)
                print("1 - Ir para a porta da direita // 2 - Ir para a porta da esquerda // 3 - Tentar abrir o cofre")
                time.sleep(a)
                escolha4 = int(input(""))
                time.sleep(a)
            else:
                print("Você abre a porta de novo.")
                time.sleep(a)
                print("Porém, o senhor não se encontra mais lá dentro")
                time.sleep(a)
                print("O Que fazer?")
                time.sleep(a)
                print("1 - Ir para a porta da direita // 2 - Ir para a porta da esquerda // 3 - Tentar abrir o cofre")
                time.sleep(a)
                escolha4 = int(input(""))
                time.sleep(a)   
        elif escolha4 == 2:
            print("Entrar pela porta da esquerda?")
            time.sleep(a)
            print("S - Sim // N - Não")
            time.sleep(a)
            certeza = input('')
            time.sleep(a)
            if certeza in 'Ss':
                print("Você abre a porta da esquerda.")
                time.sleep(a)
                break
            elif certeza in 'N' 'n':
                print("1 - Ir para a porta da direita // 2 - Ir para a porta da esquerda // 3 - Tentar abrir o cofre")
                time.sleep(a)
                escolha4 = int(input(""))                
        elif escolha4 == 3 and chave_helicoptero == False:
            print("Você se dirige até o cofre.")
            time.sleep(a)
            print("Ele é um cofre quadrado de metal.")
            time.sleep(a)
            print("Te lembra bastante um cofre de banco.")
            time.sleep(a)
            print("Tentar abri-lo?")
            time.sleep(a)
            print("S - Sim // N - Não")
            time.sleep(a)
            escolha_cofre = input('')
            time.sleep(a)
            if escolha_cofre in 'Ss':
                print("Você se aproxima do cofre, e percebe que é necessário uma senha de quatro dígitos para abri-lo.")
                time.sleep(a)
                print("Ao analisar a situação, você associa o cofre com aquele papel que o senhor havia lhe entregado.")
                time.sleep(a)
                print("Porém, ao procurar pela sua mochila e pelos seus bolsos, você percebe que perdeu o papel.")
                time.sleep(a)
                print('"Qual era a senha mesmo?"')
                time.sleep(a)
                print("Digite a senha de 4 digitos.")
                time.sleep(a)
                senha = int(input(''))
                time.sleep(a)
                if senha == 5207:
                    print("Você consegue se lembrar da senha que o senhor havia lhe dito.")
                    time.sleep(a)
                    print("Dentro do cofre, você encontra uma chave estranha, que aparenta ser a chave de algum veículo.")
                    chave_helicoptero = True
                elif senha == 2446:
                    print("Você coloca a senha, e imeidatamente começa a ouvir um apito.")
                    time.sleep(a)
                    print("Confuso você olha para os lados repetidamente.")
                    time.sleep(a)
                    print("Seu campo de visão é progressivamente bloqueado por uma fumaça.")
                    time.sleep(a)
                    print("Você sente sua cabeça cada vez mais leve...")
                    time.sleep(a)
                    print("Você morreu.")
                    time.sleep(a)
                    print("Reiniciar o jogo?")
                    time.sleep(a)
                    print("1 - Sim // 2 - Não")
                    time.sleep(a)
                    reiniciar = int(input(""))
                    time.sleep(a)
                    if reiniciar == 1:
                        restart()
                    elif reiniciar == 2:
                        sys.exit()
                else:
                    print("Senha incorreta.")
            print("1 - Ir para a porta da direita // 2 - Ir para a porta da esquerda // 3 - Tentar abrir o cofre")
            time.sleep(a)
            escolha4 = int(input(""))
            time.sleep(a) 
        else:
            print("Não há mais nada aqui.")
            time.sleep(a)
            print("1 - Ir para a porta da direita // 2 - Ir para a porta da esquerda // 3 - Tentar abrir o cofre")
            time.sleep(a)
            escolha4 = int(input("")) 
if chave_helicoptero == True:
        print("Após abrir a porta, uma forte ventania acerta seu rosto.")
        time.sleep(a)
        print("Você se encontra na cobertura do prédio.")
        time.sleep(a)
        print("Parado na sua frente, você percebe um helicóptero em uma base.")
        time.sleep(a)
        print("Assumindo que a chave adquirida no cofre tenha relação, você monta no helicóptero.")
        time.sleep(a)
        print("A chave funciona.")
        time.sleep(a)
        print("Você foge do prédio de helicóptero.")
        time.sleep(a)
        print("Olhando pelo retrovisor, você nota que o prédio etava desmoronando, até uma pilha de escombros ser a última coisa visível.")
        time.sleep(a)
        print("A risada do senhor prisioneiro ecoa pela sua cabeça.")
        time.sleep(a)
        efeitoFala(". . .")
        print('')
        time.sleep(a)
        print("Você venceu!")
        time.sleep(a)
        print("Reiniciar o jogo?")
        time.sleep(a)
        print("1 - Sim // 2 - Não")
        time.sleep(a)
        reiniciar = int(input(""))
        time.sleep(a)
else:
        print("Você precipitadamente decide sair daquela sala.")
        time.sleep(a)
        print("Fortes ventos batem no seu rosto.")
        time.sleep(a)
        print("Ventos que batem a porta pela qual você acabou de sair.")
        time.sleep(a)
        print("Agora ela se encontra emperrada.")
        time.sleep(a)
        print("Você vê um helicóptero parado em uma base a sua frente.")
        time.sleep(a)
        print("Ele parece ser a sua única opção agora.")
        time.sleep(a)
        print("Você sobe no helicóptero, e percebe que não existe algum meio de liga-lo.")
        time.sleep(a)
        print("Você encosta no acento, apoiando a sua cabeça levemente pra trás, e começa a pensar.")
        time.sleep(a)
        print("Mas não muito tempo depois, você ouve uma explosão e a sua visão fica esbranquiçada...")
        time.sleep(a)
        print("Você morreu.")
        time.sleep(a)
        print("Reiniciar o jogo?")
        time.sleep(a)
        print("1 - Sim // 2 - Não")
        time.sleep(a)
        reiniciar = int(input(""))
        time.sleep(a)
        if reiniciar == 1:
            restart()
        elif reiniciar == 2:
            sys.exit()